[package]
name = "quote_api"
version = "0.0.1"
authors = ["darkruby"]
edition = "2018"

[dependencies]
yahoo_finance_api = "1.0.2"
serde_json = "1.0"
serde = { version="1.0.117", features = ["derive"] } 
chrono = "0.4.19"
actix-web = "3"


[[bin]]
name="server"