[package]
name = "quote_api"
version = "0.0.1"
authors = ["@darkest_ruby"]
edition = "2018"
description = "HTTP API to fetch crypto/shares quotes (uses Y! finance)" 

[dependencies]
yahoo_finance_api = "1.0.2"
serde_json = "1.0"
serde = { version="1.0.117", features = ["derive"] } 
chrono = "0.4.19"
actix-web = "3"
actix-web-httpauth="0.5.0"
structopt = "0.3.20"
regex = "1"
log = "0.4"
simple_logger = "1.11"




[[bin]]
name="server"